### PR TITLE
[-] MO: Wrong key if fields has consecutive spaces and HTML compression ...

### PR DESCRIPTION
**Pull request by doekia**
[-] MO: Wrong key if fields has consecutive spaces and HTML compression active

### CODE REVIEW

**Comment by gaillafr** [comment]
Hi @quadrateam, could you please check this PR and confirm it's OK for you if I merge it?
Thank you, kind regards.

**Comment by doekia** [comment]
Sorry, but I refuse you the right to include my patch to your solution.
This patch is indeed copyright (d)oekia. If you do not agree with the term of crediting my contribution within the copyright notice, just don't use it!

**Comment by gaillafr** [comment]
What's wrong with you @doekia?! Why creating a pull request and ask people to not using it?

**Comment by doekia** [comment]
Cause I was willing to contribute. This is not the case anymore since PrestaShop classified me as "non-grata". Therefore no more contribution! Ask XDT or whom it may- concern why contributors are treated like shit !

**Comment by PuffDaddyCat** [comment]
Did I read "copyright" and "open source contribution" in the same sentence? Did someone put magic mushrooms in my croquettes?

**Comment by quadrateam** [comment]
@gaillafr we wiil do a test pass today.

**Pull request closed without merging**
